### ISSUE TITLE
Alle repositories zumindest für "core"-Gruppe zugänglich machen

### ISSUE THREAD

**Issue by rnestler** [HSR-Stud/Sandkasten#5]
Ich halte ja grundsätzlich wenig von privaten Repositories.

Aber wenn wenigstens alle repos für core zugänglich wären, hätte ich bemerkt, dass es bereits ein DigPro1 repo gibt und hätte mir ein wenig Arbeit gespart... siehe https://github.com/rnestler/DigPro1

**Comment by rnestler** [comment]
Da ich mittlerweile mit dem Studium fertig bin schlisse ich das mal :wink:

**Comment by dbrgn** [comment]
@rnestler das hast du schön geschlissen :smile:
